security:

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: 'admin'
                        roles: 'ROLE_ADMIN'
                    phabulous:
                        password: 'phabulous'
                        roles: 'ROLE_USER'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            logout: true
            http_digest:
                secret: '%secret%'
                realm: 'Phabulous'
            anonymous: ~

    access_control:
        - { path: ^/cache/refresh,          roles: ROLE_ADMIN }
        - { path: ^/phacility/edit,         roles: ROLE_ADMIN }
        - { path: ^/,                       roles: ROLE_USER }